name: Cypress Tests
on: [push]
jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4' # Especifique a versão do PHP que seu projeto requer
        extensions: mbstring, xml, ctype, json, bcmath, curl
        ini-values: post_max_size=256M, upload_max_filesize=256M
        tools: composer:v2
    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Generate Key
      run: php artisan key:generate
    - name: Start Laravel Server
      run: php artisan serve &
    - name: Run Cypress Tests
      uses: cypress-io/github-action@v6
      with:
        start: npm run dev
        wait-on: http://localhost:8000
        record: true
        parallel: true
        publish-summary: true
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
